version: "3.9"
services:
  library:
    image: postgres:14.5
    environment:
        POSTGRES_DB: SAVKO_204
        POSTGRES_USER: SAVKO_204
        POSTGRES_PASSWORD: SAVKO_204
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  trains:
    image: postgres:14.5
    environment:
        POSTGRES_DB: SAVKO_204
        POSTGRES_USER: SAVKO_204
        POSTGRES_PASSWORD: SAVKO_204
    volumes:
      - ./docker/db/scripts/trains:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  
  hospital:
    image: postgres:14.5
    environment:
        POSTGRES_DB: SAVKO_204
        POSTGRES_USER: SAVKO_204
        POSTGRES_PASSWORD: SAVKO_204
    volumes:
      - ./docker/db/scripts/hospital:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
